/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/apiServices`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/api`; params?: Router.UnknownInputParams; } | { pathname: `/../storage/locationStore`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/routes/useImageSelection`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/routes/useRouteTemplates`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/routes/useRouteForm`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/routes/useRouteSubmission`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chooseGym` | `/chooseGym`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/routes/createRoute`; params?: Router.UnknownInputParams; } | { pathname: `/routes/routeDetail`; params?: Router.UnknownInputParams; } | { pathname: `/routes/routeImageCreator`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../utils/apiServices`; params?: Router.UnknownOutputParams; } | { pathname: `/../utils/api`; params?: Router.UnknownOutputParams; } | { pathname: `/../storage/locationStore`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/routes/useImageSelection`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/routes/useRouteTemplates`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/routes/useRouteForm`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/routes/useRouteSubmission`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chooseGym` | `/chooseGym`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/createRoute`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/routeDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/routeImageCreator`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/../utils/apiServices${`?${string}` | `#${string}` | ''}` | `/../utils/api${`?${string}` | `#${string}` | ''}` | `/../storage/locationStore${`?${string}` | `#${string}` | ''}` | `/../hooks/routes/useImageSelection${`?${string}` | `#${string}` | ''}` | `/../hooks/routes/useRouteTemplates${`?${string}` | `#${string}` | ''}` | `/../hooks/routes/useRouteForm${`?${string}` | `#${string}` | ''}` | `/../hooks/routes/useRouteSubmission${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chooseGym${`?${string}` | `#${string}` | ''}` | `/chooseGym${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/routes/createRoute${`?${string}` | `#${string}` | ''}` | `/routes/routeDetail${`?${string}` | `#${string}` | ''}` | `/routes/routeImageCreator${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/apiServices`; params?: Router.UnknownInputParams; } | { pathname: `/../utils/api`; params?: Router.UnknownInputParams; } | { pathname: `/../storage/locationStore`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/routes/useImageSelection`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/routes/useRouteTemplates`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/routes/useRouteForm`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/routes/useRouteSubmission`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chooseGym` | `/chooseGym`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/routes/createRoute`; params?: Router.UnknownInputParams; } | { pathname: `/routes/routeDetail`; params?: Router.UnknownInputParams; } | { pathname: `/routes/routeImageCreator`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
