/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chooseGym` | `/chooseGym`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/edit-profile` | `/profile/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/profile` | `/profile/profile`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/routes/createRoute`; params?: Router.UnknownInputParams; } | { pathname: `/routes/routeDetail`; params?: Router.UnknownInputParams; } | { pathname: `/routes/routeImageCreator`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/chooseGym` | `/chooseGym`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/edit-profile` | `/profile/edit-profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/profile` | `/profile/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/register`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/createRoute`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/routeDetail`; params?: Router.UnknownOutputParams; } | { pathname: `/routes/routeImageCreator`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/chooseGym${`?${string}` | `#${string}` | ''}` | `/chooseGym${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/edit-profile${`?${string}` | `#${string}` | ''}` | `/profile/edit-profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/profile${`?${string}` | `#${string}` | ''}` | `/profile/profile${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/auth/register${`?${string}` | `#${string}` | ''}` | `/routes/createRoute${`?${string}` | `#${string}` | ''}` | `/routes/routeDetail${`?${string}` | `#${string}` | ''}` | `/routes/routeImageCreator${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/chooseGym` | `/chooseGym`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/edit-profile` | `/profile/edit-profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/profile` | `/profile/profile`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/auth/register`; params?: Router.UnknownInputParams; } | { pathname: `/routes/createRoute`; params?: Router.UnknownInputParams; } | { pathname: `/routes/routeDetail`; params?: Router.UnknownInputParams; } | { pathname: `/routes/routeImageCreator`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
